export const POOLS = [
  // TON — STON.fi
  { id: 1,  pair: 'TON/USDT',      chain: 'TON',     dex: 'STON.fi',    apy: 18.5,  tvl: 45200000,  vol24h: 3200000,  ilRisk: 'Medium'   },
  { id: 2,  pair: 'TON/USDC',      chain: 'TON',     dex: 'STON.fi',    apy: 16.8,  tvl: 32100000,  vol24h: 2100000,  ilRisk: 'Medium'   },
  { id: 3,  pair: 'STON/TON',      chain: 'TON',     dex: 'STON.fi',    apy: 42.3,  tvl: 8700000,   vol24h: 1400000,  ilRisk: 'High'     },
  { id: 4,  pair: 'BOLT/TON',      chain: 'TON',     dex: 'STON.fi',    apy: 67.4,  tvl: 2100000,   vol24h: 890000,   ilRisk: 'Very High' },
  { id: 5,  pair: 'jUSDT/jUSDC',   chain: 'TON',     dex: 'STON.fi',    apy: 5.2,   tvl: 22400000,  vol24h: 4100000,  ilRisk: 'None'     },
  { id: 6,  pair: 'STON/USDT',     chain: 'TON',     dex: 'STON.fi',    apy: 55.3,  tvl: 3200000,   vol24h: 1100000,  ilRisk: 'Very High' },
  { id: 7,  pair: 'NOT/TON',       chain: 'TON',     dex: 'STON.fi',    apy: 78.9,  tvl: 4100000,   vol24h: 2200000,  ilRisk: 'Very High' },
  // TON — DeDust
  { id: 8,  pair: 'TON/USDT',      chain: 'TON',     dex: 'DeDust',     apy: 21.2,  tvl: 38500000,  vol24h: 2900000,  ilRisk: 'Medium'   },
  { id: 9,  pair: 'TON/WBTC',      chain: 'TON',     dex: 'DeDust',     apy: 15.7,  tvl: 18300000,  vol24h: 1200000,  ilRisk: 'Medium'   },
  { id: 10, pair: 'TON/ETH',       chain: 'TON',     dex: 'DeDust',     apy: 19.4,  tvl: 12600000,  vol24h: 980000,   ilRisk: 'Medium'   },
  { id: 11, pair: 'SCALE/TON',     chain: 'TON',     dex: 'DeDust',     apy: 89.2,  tvl: 1400000,   vol24h: 670000,   ilRisk: 'Very High' },
  { id: 12, pair: 'FNZ/USDT',      chain: 'TON',     dex: 'DeDust',     apy: 112.4, tvl: 800000,    vol24h: 450000,   ilRisk: 'Very High' },
  { id: 13, pair: 'hTON/TON',      chain: 'TON',     dex: 'DeDust',     apy: 6.8,   tvl: 28900000,  vol24h: 1800000,  ilRisk: 'Low'      },
  { id: 14, pair: 'tgBTC/TON',     chain: 'TON',     dex: 'DeDust',     apy: 14.2,  tvl: 9800000,   vol24h: 780000,   ilRisk: 'Medium'   },
  // Polygon — Uniswap v3
  { id: 15, pair: 'WETH/USDC',     chain: 'Polygon', dex: 'Uniswap v3', apy: 12.3,  tvl: 89400000,  vol24h: 12400000, ilRisk: 'Medium'   },
  { id: 16, pair: 'WBTC/WETH',     chain: 'Polygon', dex: 'Uniswap v3', apy: 8.7,   tvl: 67200000,  vol24h: 8900000,  ilRisk: 'Low'      },
  { id: 17, pair: 'MATIC/USDC',    chain: 'Polygon', dex: 'Uniswap v3', apy: 18.9,  tvl: 34700000,  vol24h: 5600000,  ilRisk: 'Medium'   },
  { id: 18, pair: 'WETH/USDT',     chain: 'Polygon', dex: 'Uniswap v3', apy: 11.8,  tvl: 78300000,  vol24h: 10200000, ilRisk: 'Medium'   },
  { id: 19, pair: 'WBTC/USDC',     chain: 'Polygon', dex: 'Uniswap v3', apy: 7.2,   tvl: 52100000,  vol24h: 7100000,  ilRisk: 'Low'      },
  // Polygon — QuickSwap
  { id: 20, pair: 'MATIC/USDC',    chain: 'Polygon', dex: 'QuickSwap',  apy: 22.4,  tvl: 28900000,  vol24h: 4200000,  ilRisk: 'Medium'   },
  { id: 21, pair: 'QUICK/MATIC',   chain: 'Polygon', dex: 'QuickSwap',  apy: 45.8,  tvl: 9200000,   vol24h: 2800000,  ilRisk: 'High'     },
  { id: 22, pair: 'WETH/MATIC',    chain: 'Polygon', dex: 'QuickSwap',  apy: 19.7,  tvl: 41300000,  vol24h: 6100000,  ilRisk: 'Medium'   },
  { id: 23, pair: 'USDC/USDT',     chain: 'Polygon', dex: 'QuickSwap',  apy: 4.8,   tvl: 156200000, vol24h: 21000000, ilRisk: 'None'     },
  { id: 24, pair: 'WBTC/MATIC',    chain: 'Polygon', dex: 'QuickSwap',  apy: 24.3,  tvl: 15800000,  vol24h: 3400000,  ilRisk: 'High'     },
  { id: 25, pair: 'ANKR/MATIC',    chain: 'Polygon', dex: 'QuickSwap',  apy: 31.2,  tvl: 7400000,   vol24h: 1900000,  ilRisk: 'High'     },
  // Polygon — Balancer
  { id: 26, pair: 'WETH/WBTC/USDC',chain: 'Polygon', dex: 'Balancer',   apy: 9.4,   tvl: 45600000,  vol24h: 7800000,  ilRisk: 'Low'      },
  { id: 27, pair: 'MATIC/WETH/BAL', chain: 'Polygon', dex: 'Balancer',  apy: 16.2,  tvl: 22100000,  vol24h: 3200000,  ilRisk: 'Medium'   },
  { id: 28, pair: 'stMATIC/MATIC',  chain: 'Polygon', dex: 'Balancer',  apy: 7.8,   tvl: 34200000,  vol24h: 2900000,  ilRisk: 'Low'      },
  { id: 29, pair: 'USDC/USDT/DAI',  chain: 'Polygon', dex: 'Balancer',  apy: 4.1,   tvl: 98700000,  vol24h: 15600000, ilRisk: 'None'     },
  { id: 30, pair: 'BAL/WETH',       chain: 'Polygon', dex: 'Balancer',  apy: 28.4,  tvl: 8300000,   vol24h: 2100000,  ilRisk: 'High'     },
  // Base — Aerodrome
  { id: 31, pair: 'WETH/USDC',     chain: 'Base',    dex: 'Aerodrome', apy: 14.2,  tvl: 112400000, vol24h: 18700000, ilRisk: 'Medium'   },
  { id: 32, pair: 'cbETH/WETH',    chain: 'Base',    dex: 'Aerodrome', apy: 7.3,   tvl: 78200000,  vol24h: 8900000,  ilRisk: 'Low'      },
  { id: 33, pair: 'USDC/USDbC',    chain: 'Base',    dex: 'Aerodrome', apy: 5.1,   tvl: 198400000, vol24h: 24100000, ilRisk: 'None'     },
  { id: 34, pair: 'WETH/AERO',     chain: 'Base',    dex: 'Aerodrome', apy: 38.7,  tvl: 24300000,  vol24h: 5400000,  ilRisk: 'High'     },
  { id: 35, pair: 'cbBTC/WETH',    chain: 'Base',    dex: 'Aerodrome', apy: 9.8,   tvl: 45100000,  vol24h: 7200000,  ilRisk: 'Medium'   },
  { id: 36, pair: 'USDC/DAI',      chain: 'Base',    dex: 'Aerodrome', apy: 4.6,   tvl: 67800000,  vol24h: 9800000,  ilRisk: 'None'     },
  // Base — Uniswap v3
  { id: 37, pair: 'WETH/USDC',     chain: 'Base',    dex: 'Uniswap v3',apy: 11.8,  tvl: 89200000,  vol24h: 16200000, ilRisk: 'Medium'   },
  { id: 38, pair: 'cbETH/WETH',    chain: 'Base',    dex: 'Uniswap v3',apy: 6.1,   tvl: 52400000,  vol24h: 6700000,  ilRisk: 'Low'      },
  // BNB — PancakeSwap
  { id: 39, pair: 'WBNB/USDT',     chain: 'BNB',     dex: 'PancakeSwap',apy: 19.4, tvl: 134600000, vol24h: 28400000, ilRisk: 'Medium'   },
  { id: 40, pair: 'BTCB/WBNB',     chain: 'BNB',     dex: 'PancakeSwap',apy: 12.1, tvl: 87400000,  vol24h: 14600000, ilRisk: 'Medium'   },
  { id: 41, pair: 'ETH/WBNB',      chain: 'BNB',     dex: 'PancakeSwap',apy: 16.8, tvl: 64200000,  vol24h: 11200000, ilRisk: 'Medium'   },
  { id: 42, pair: 'USDT/USDC',     chain: 'BNB',     dex: 'PancakeSwap',apy: 5.3,  tvl: 213800000, vol24h: 34700000, ilRisk: 'None'     },
  { id: 43, pair: 'CAKE/WBNB',     chain: 'BNB',     dex: 'PancakeSwap',apy: 44.2, tvl: 31200000,  vol24h: 8900000,  ilRisk: 'High'     },
  { id: 44, pair: 'BTCB/USDT',     chain: 'BNB',     dex: 'PancakeSwap',apy: 8.7,  tvl: 76400000,  vol24h: 12300000, ilRisk: 'Low'      },
  { id: 45, pair: 'ETH/USDT',      chain: 'BNB',     dex: 'PancakeSwap',apy: 11.3, tvl: 58700000,  vol24h: 9400000,  ilRisk: 'Medium'   },
]

export const LENDING = [
  { id: 1,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'USDC',  supplyAPY: 4.21, borrowAPY: 6.82, utilization: 78, tvl: 234500000 },
  { id: 2,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'USDT',  supplyAPY: 3.91, borrowAPY: 6.14, utilization: 74, tvl: 189200000 },
  { id: 3,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'WETH',  supplyAPY: 1.82, borrowAPY: 3.24, utilization: 62, tvl: 456700000 },
  { id: 4,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'WBTC',  supplyAPY: 0.94, borrowAPY: 2.41, utilization: 48, tvl: 312400000 },
  { id: 5,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'MATIC', supplyAPY: 2.31, borrowAPY: 4.12, utilization: 67, tvl: 87600000  },
  { id: 6,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'DAI',   supplyAPY: 3.74, borrowAPY: 5.93, utilization: 72, tvl: 145300000 },
  { id: 7,  protocol: 'Evaa',       chain: 'TON',     asset: 'TON',   supplyAPY: 5.12, borrowAPY: 8.34, utilization: 69, tvl: 78400000  },
  { id: 8,  protocol: 'Evaa',       chain: 'TON',     asset: 'USDT',  supplyAPY: 6.23, borrowAPY: 9.11, utilization: 81, tvl: 45600000  },
  { id: 9,  protocol: 'Evaa',       chain: 'TON',     asset: 'USDC',  supplyAPY: 5.81, borrowAPY: 8.72, utilization: 77, tvl: 32100000  },
  { id: 10, protocol: 'Evaa',       chain: 'TON',     asset: 'tgBTC', supplyAPY: 1.43, borrowAPY: 3.82, utilization: 45, tvl: 18700000  },
  { id: 11, protocol: 'Tonstakers', chain: 'TON',     asset: 'TON',   supplyAPY: 5.83, borrowAPY: null, utilization: null, tvl: 234000000 },
  { id: 12, protocol: 'Bemo',       chain: 'TON',     asset: 'TON',   supplyAPY: 6.11, borrowAPY: null, utilization: null, tvl: 178000000 },
  // Base — AAVE v3
  { id: 13, protocol: 'AAVE v3',   chain: 'Base',    asset: 'WETH',  supplyAPY: 1.94, borrowAPY: 3.41, utilization: 64, tvl: 312400000 },
  { id: 14, protocol: 'AAVE v3',   chain: 'Base',    asset: 'USDC',  supplyAPY: 4.87, borrowAPY: 7.12, utilization: 82, tvl: 198700000 },
  { id: 15, protocol: 'AAVE v3',   chain: 'Base',    asset: 'cbETH', supplyAPY: 1.12, borrowAPY: 2.43, utilization: 51, tvl: 134200000 },
  { id: 16, protocol: 'AAVE v3',   chain: 'Base',    asset: 'USDbC', supplyAPY: 4.31, borrowAPY: 6.74, utilization: 76, tvl: 87400000  },
  // BNB — AAVE v3
  { id: 17, protocol: 'AAVE v3',   chain: 'BNB',     asset: 'USDT',  supplyAPY: 5.21, borrowAPY: 7.84, utilization: 79, tvl: 234100000 },
  { id: 18, protocol: 'AAVE v3',   chain: 'BNB',     asset: 'USDC',  supplyAPY: 4.93, borrowAPY: 7.41, utilization: 76, tvl: 189300000 },
  { id: 19, protocol: 'AAVE v3',   chain: 'BNB',     asset: 'WBNB',  supplyAPY: 1.78, borrowAPY: 3.12, utilization: 59, tvl: 156800000 },
  { id: 20, protocol: 'AAVE v3',   chain: 'BNB',     asset: 'BTCB',  supplyAPY: 0.87, borrowAPY: 2.14, utilization: 44, tvl: 213400000 },
  { id: 21, protocol: 'AAVE v3',   chain: 'BNB',     asset: 'ETH',   supplyAPY: 1.63, borrowAPY: 3.08, utilization: 57, tvl: 98700000  },
]

// Kept for any legacy references — consumers should use TON_STRATEGIES / POLYGON_STRATEGIES
export const STRATEGIES = []

// ─── TON Strategies ─────────────────────────────────────────────────────────
// Each strategy activates via one TON Connect transaction (multi-message).

export const TON_STRATEGIES = [
  {
    id: 'ton-capital-shield',
    chain: 'TON',
    tier: 'Super Safe',
    name: 'Capital Shield',
    apyMin: 5,
    apyMax: 7,
    color: '#00d4aa',
    riskScore: 1,
    protocols: ['Tonstakers', 'Bemo'],
    ilRisk: false,
    liquidationRisk: false,
    description: 'Native TON liquid staking across two battle-tested validators. 60% to Tonstakers (tsTON) and 40% to Bemo (stTON). Both tokens accrue staking rewards automatically — no LP, no IL risk, no liquidation. One TON Connect signature sends to both staking pools simultaneously.',
    allocation: [
      { label: 'Tonstakers — tsTON', pct: 60, color: '#0098ea' },
      { label: 'Bemo — stTON',       pct: 40, color: '#00bfff' },
    ],
    txMessages: 2,
    gasEstimate: '0.05 TON',
  },
  {
    id: 'ton-liquid-yield',
    chain: 'TON',
    tier: 'Safe',
    name: 'Liquid Yield',
    apyMin: 8,
    apyMax: 14,
    color: '#0098ea',
    riskScore: 2,
    protocols: ['Hipo', 'DeDust', 'Evaa'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'Diversified staking + lending. 45% to Hipo (hTON liquid staking), 35% to DeDust hTON/TON liquidity pool (low IL — both are TON-correlated), 20% supplied to Evaa lending market. Three contracts, one wallet signature.',
    allocation: [
      { label: 'Hipo — hTON staking',    pct: 45, color: '#0098ea' },
      { label: 'DeDust — hTON/TON LP',   pct: 35, color: '#0076bb' },
      { label: 'Evaa — TON supply',       pct: 20, color: '#00d4aa' },
    ],
    txMessages: 4,
    gasEstimate: '0.4 TON',
  },
  {
    id: 'ton-amm-optimizer',
    chain: 'TON',
    tier: 'Middle',
    name: 'AMM Optimizer',
    apyMin: 18,
    apyMax: 35,
    color: '#f97316',
    riskScore: 3,
    protocols: ['STON.fi', 'DeDust'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'Dual-AMM LP strategy. 50% to STON.fi v2 TON/USDT pool (router: EQBCl1...Ried) and 50% to DeDust TON/USDT pool (factory: EQBfBW...J67). Weekly rebalancing toward the pool with higher fee yield. IL risk if TON price moves >20%.',
    allocation: [
      { label: 'STON.fi v2 — TON/USDT',  pct: 50, color: '#0098ea' },
      { label: 'DeDust — TON/USDT LP',   pct: 50, color: '#0076bb' },
    ],
    txMessages: 4,
    gasEstimate: '0.7 TON',
  },
  {
    id: 'ton-alpha-hunt',
    chain: 'TON',
    tier: 'Alpha Seeker',
    name: 'Alpha Hunt',
    apyMin: 45,
    apyMax: 110,
    color: '#ef4444',
    riskScore: 4,
    protocols: ['STON.fi', 'DeDust'],
    ilRisk: true,
    liquidationRisk: true,
    description: 'High-volatility pool rotation targeting incentivized pairs. 40% STON.fi STON/TON (~42% APY), 35% DeDust SCALE/TON (~89% APY), 25% STON.fi NOT/TON (~79% APY). Pools have <6 months track record. Token prices can go to zero. Full capital loss is possible.',
    allocation: [
      { label: 'STON.fi — STON/TON',   pct: 40, color: '#0098ea' },
      { label: 'DeDust — SCALE/TON',   pct: 35, color: '#ef4444' },
      { label: 'STON.fi — NOT/TON',    pct: 25, color: '#f97316' },
    ],
    txMessages: 6,
    gasEstimate: '1.2 TON',
  },
]

// ─── Polygon Strategies ──────────────────────────────────────────────────────
// Each strategy activates via Multicall3 (one eth_sendTransaction after approvals).

export const POLYGON_STRATEGIES = [
  {
    id: 'poly-stablecoin-vault',
    chain: 'Polygon',
    tier: 'Super Safe',
    name: 'Stablecoin Vault',
    apyMin: 3,
    apyMax: 6,
    color: '#00d4aa',
    riskScore: 1,
    protocols: ['AAVE v3', 'QuickSwap'],
    ilRisk: false,
    liquidationRisk: false,
    description: 'Stablecoin-only yield via AAVE v3 (pool: 0x794a...14aD) and QuickSwap v2. 55% AAVE USDC supply (~4.2% APY), 30% AAVE USDT supply (~3.9% APY), 15% QuickSwap USDC/USDT LP (~4.8% APY). One Multicall3 transaction after token approvals.',
    allocation: [
      { label: 'AAVE v3 — USDC supply', pct: 55, color: '#8247e5' },
      { label: 'AAVE v3 — USDT supply', pct: 30, color: '#6432b8' },
      { label: 'QuickSwap — USDC/USDT', pct: 15, color: '#9b59b6' },
    ],
    approvals: ['USDC → AAVE', 'USDT → AAVE', 'USDC → QuickSwap', 'USDT → QuickSwap'],
    gasEstimate: '~0.02 MATIC',
  },
  {
    id: 'poly-correlated-pairs',
    chain: 'Polygon',
    tier: 'Safe',
    name: 'Correlated Pairs',
    apyMin: 8,
    apyMax: 14,
    color: '#0098ea',
    riskScore: 2,
    protocols: ['Uniswap v3', 'AAVE v3'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'Low-IL concentrated liquidity with a lending buffer. 45% Uniswap v3 WBTC/WETH ±5% range (NonfungiblePositionManager: 0xC364...FE88), 35% Uniswap v3 WETH/USDC ±10% range, 20% AAVE WETH supply. Correlated pairs keep IL minimal.',
    allocation: [
      { label: 'Uniswap v3 — WBTC/WETH', pct: 45, color: '#f97316' },
      { label: 'Uniswap v3 — WETH/USDC', pct: 35, color: '#fb923c' },
      { label: 'AAVE v3 — WETH supply',  pct: 20, color: '#8247e5' },
    ],
    approvals: ['WBTC → Uni v3', 'WETH → Uni v3', 'WETH → AAVE'],
    gasEstimate: '~0.04 MATIC',
  },
  {
    id: 'poly-yield-accelerator',
    chain: 'Polygon',
    tier: 'Middle',
    name: 'Yield Accelerator',
    apyMin: 18,
    apyMax: 35,
    color: '#f97316',
    riskScore: 3,
    protocols: ['QuickSwap', 'Uniswap v3'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'MATIC-centric LP farming. 40% QuickSwap MATIC/USDC (router: 0xa5E0...78ff, ~22% APY), 35% QuickSwap WETH/MATIC (~20% APY), 25% Uniswap v3 MATIC/USDC tight range (~19% APY). Significant IL if MATIC price diverges.',
    allocation: [
      { label: 'QuickSwap — MATIC/USDC', pct: 40, color: '#8247e5' },
      { label: 'QuickSwap — WETH/MATIC', pct: 35, color: '#6a35d4' },
      { label: 'Uniswap v3 — MATIC/USDC',pct: 25, color: '#f97316' },
    ],
    approvals: ['USDC → QuickSwap', 'WETH → QuickSwap', 'USDC → Uni v3'],
    gasEstimate: '~0.05 MATIC',
  },
  {
    id: 'poly-alpha-hunt',
    chain: 'Polygon',
    tier: 'Alpha Seeker',
    name: 'Alpha Hunt',
    apyMin: 30,
    apyMax: 80,
    color: '#ef4444',
    riskScore: 4,
    protocols: ['QuickSwap', 'Balancer'],
    ilRisk: true,
    liquidationRisk: true,
    description: 'High-yield pools with governance token exposure. 35% Balancer WETH/WBTC/USDC pool (vault: 0xBA12...2C8, ~9% base + BAL emissions), 30% QuickSwap QUICK/MATIC (~46% APY), 20% Balancer BAL/WETH (~28% APY), 15% QuickSwap ANKR/MATIC (~31% APY).',
    allocation: [
      { label: 'Balancer — WETH/WBTC/USDC', pct: 35, color: '#8247e5' },
      { label: 'QuickSwap — QUICK/MATIC',   pct: 30, color: '#6a35d4' },
      { label: 'Balancer — BAL/WETH',        pct: 20, color: '#9b59b6' },
      { label: 'QuickSwap — ANKR/MATIC',     pct: 15, color: '#ef4444' },
    ],
    approvals: ['WETH → Balancer', 'WBTC → Balancer', 'USDC → Balancer', 'QUICK → QuickSwap'],
    gasEstimate: '~0.06 MATIC',
  },
]

// ─── Base Strategies ─────────────────────────────────────────────────────────

export const BASE_STRATEGIES = [
  {
    id: 'base-stablecoin-vault',
    chain: 'Base',
    tier: 'Super Safe',
    name: 'Stablecoin Vault',
    apyMin: 4,
    apyMax: 7,
    color: '#00d4aa',
    riskScore: 1,
    protocols: ['AAVE v3', 'Aerodrome'],
    ilRisk: false,
    liquidationRisk: false,
    description: 'Stablecoin yield on Base. 60% AAVE v3 USDC supply (~4.9% APY), 15% AAVE v3 USDbC supply (~4.3% APY), 25% Aerodrome USDC/USDbC stable LP (~5.1% APY). Near-zero IL — both assets are USD-pegged. One Multicall3 transaction after approvals.',
    allocation: [
      { label: 'AAVE v3 — USDC supply',         pct: 60, color: '#2563eb' },
      { label: 'AAVE v3 — USDbC supply',         pct: 15, color: '#3b82f6' },
      { label: 'Aerodrome — USDC/USDbC stable',  pct: 25, color: '#6366f1' },
    ],
    approvals: ['USDC → Multicall3', 'USDbC → Multicall3'],
    gasEstimate: '~0.002 ETH',
  },
  {
    id: 'base-correlated-pairs',
    chain: 'Base',
    tier: 'Safe',
    name: 'Correlated Pairs',
    apyMin: 6,
    apyMax: 12,
    color: '#0098ea',
    riskScore: 2,
    protocols: ['AAVE v3', 'Aerodrome'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'ETH-correlated assets for minimal IL. 40% AAVE v3 cbETH supply (~1.1% APY + staking yield), 60% Aerodrome cbETH/WETH volatile LP (~7.3% APY). Both assets track ETH price — IL is minimal as they move together.',
    allocation: [
      { label: 'AAVE v3 — cbETH supply',       pct: 40, color: '#2563eb' },
      { label: 'Aerodrome — cbETH/WETH LP',    pct: 60, color: '#6366f1' },
    ],
    approvals: ['cbETH → Multicall3', 'WETH → Multicall3'],
    gasEstimate: '~0.002 ETH',
  },
  {
    id: 'base-yield-accelerator',
    chain: 'Base',
    tier: 'Middle',
    name: 'Yield Accelerator',
    apyMin: 12,
    apyMax: 24,
    color: '#f97316',
    riskScore: 3,
    protocols: ['AAVE v3', 'Aerodrome'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'WETH + USDC split across lending and LP. 20% AAVE v3 WETH supply, 80% Aerodrome WETH/USDC volatile LP (~14.2% APY). Higher IL exposure if ETH diverges from USDC — rebalance recommended if ETH moves >30%.',
    allocation: [
      { label: 'AAVE v3 — WETH supply',       pct: 20, color: '#2563eb' },
      { label: 'Aerodrome — WETH/USDC LP',    pct: 80, color: '#f97316' },
    ],
    approvals: ['WETH → Multicall3', 'USDC → Multicall3'],
    gasEstimate: '~0.002 ETH',
  },
  {
    id: 'base-alpha-hunt',
    chain: 'Base',
    tier: 'Alpha Seeker',
    name: 'Alpha Hunt',
    apyMin: 25,
    apyMax: 65,
    color: '#ef4444',
    riskScore: 4,
    protocols: ['AAVE v3', 'Aerodrome'],
    ilRisk: true,
    liquidationRisk: true,
    description: 'AERO governance token exposure for maximum Base yield. 30% AAVE v3 WETH, 70% Aerodrome WETH/AERO LP (~38.7% APY including AERO emissions). AERO token has high volatility — full capital loss is possible if AERO trends to zero.',
    allocation: [
      { label: 'AAVE v3 — WETH supply',    pct: 30, color: '#2563eb' },
      { label: 'Aerodrome — WETH/AERO LP', pct: 70, color: '#ef4444' },
    ],
    approvals: ['WETH → Multicall3', 'AERO → Multicall3'],
    gasEstimate: '~0.002 ETH',
  },
]

// ─── BNB Strategies ──────────────────────────────────────────────────────────

export const BNB_STRATEGIES = [
  {
    id: 'bnb-stablecoin-vault',
    chain: 'BNB',
    tier: 'Super Safe',
    name: 'Stablecoin Vault',
    apyMin: 4,
    apyMax: 8,
    color: '#00d4aa',
    riskScore: 1,
    protocols: ['AAVE v3', 'PancakeSwap'],
    ilRisk: false,
    liquidationRisk: false,
    description: 'Stablecoin yield on BNB Chain. 50% AAVE v3 USDT supply (~5.2% APY), 50% PancakeSwap USDT/USDC LP (~5.3% APY). Near-zero IL — USD-pegged assets. One Multicall3 transaction after approvals.',
    allocation: [
      { label: 'AAVE v3 — USDT supply',        pct: 50, color: '#f59e0b' },
      { label: 'PancakeSwap — USDT/USDC LP',   pct: 50, color: '#d97706' },
    ],
    approvals: ['USDT → Multicall3', 'USDC → Multicall3'],
    gasEstimate: '~0.002 BNB',
  },
  {
    id: 'bnb-correlated-pairs',
    chain: 'BNB',
    tier: 'Safe',
    name: 'Correlated Pairs',
    apyMin: 7,
    apyMax: 15,
    color: '#0098ea',
    riskScore: 2,
    protocols: ['AAVE v3', 'PancakeSwap'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'BTC + ETH correlated pair strategy. 30% AAVE v3 BTCB supply (~0.9% APY), 70% PancakeSwap BTCB/ETH LP (~12.1% APY). Both track BTC and ETH respectively — correlated assets keep IL moderate.',
    allocation: [
      { label: 'AAVE v3 — BTCB supply',      pct: 30, color: '#f59e0b' },
      { label: 'PancakeSwap — BTCB/ETH LP',  pct: 70, color: '#d97706' },
    ],
    approvals: ['BTCB → Multicall3', 'ETH → Multicall3'],
    gasEstimate: '~0.002 BNB',
  },
  {
    id: 'bnb-yield-accelerator',
    chain: 'BNB',
    tier: 'Middle',
    name: 'Yield Accelerator',
    apyMin: 14,
    apyMax: 28,
    color: '#f97316',
    riskScore: 3,
    protocols: ['AAVE v3', 'PancakeSwap'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'WBNB-centric yield. 40% AAVE v3 WBNB supply (~1.8% APY), 60% PancakeSwap WBNB/USDT LP (~19.4% APY). IL risk if BNB price diverges significantly from USDT.',
    allocation: [
      { label: 'AAVE v3 — WBNB supply',        pct: 40, color: '#f59e0b' },
      { label: 'PancakeSwap — WBNB/USDT LP',   pct: 60, color: '#f97316' },
    ],
    approvals: ['WBNB → Multicall3', 'USDT → Multicall3'],
    gasEstimate: '~0.002 BNB',
  },
  {
    id: 'bnb-alpha-hunt',
    chain: 'BNB',
    tier: 'Alpha Seeker',
    name: 'Alpha Hunt',
    apyMin: 28,
    apyMax: 75,
    color: '#ef4444',
    riskScore: 4,
    protocols: ['AAVE v3', 'PancakeSwap'],
    ilRisk: true,
    liquidationRisk: true,
    description: 'CAKE governance token exposure for high BNB Chain yield. 30% AAVE v3 WBNB, 70% PancakeSwap CAKE/WBNB LP (~44.2% APY including CAKE emissions). CAKE price is volatile — high IL risk, partial capital loss possible.',
    allocation: [
      { label: 'AAVE v3 — WBNB supply',      pct: 30, color: '#f59e0b' },
      { label: 'PancakeSwap — CAKE/WBNB LP', pct: 70, color: '#ef4444' },
    ],
    approvals: ['WBNB → Multicall3', 'CAKE → Multicall3'],
    gasEstimate: '~0.002 BNB',
  },
]

export const SECURITY_DATA = {
  tonsecStatus: 'Operational',
  vaultHealth: 98.7,
  insuranceFund: 4200000,
  totalScreened: 1847293,
  anomaliesDetected: 3,
  pausedContracts: 0,
  timelockHours: 48,
  multiSig: '3-of-5',
  audits: [
    { firm: 'Trail of Bits',    date: '2024-11-15', scope: 'Full protocol audit',           status: 'Passed',  findings: '0 critical · 2 medium (fixed)' },
    { firm: 'Certik',           date: '2024-09-08', scope: 'FunC smart contracts',           status: 'Passed',  findings: '0 critical · 1 high (fixed) · 4 medium (fixed)' },
    { firm: 'SlowMist',         date: '2024-06-22', scope: 'Bridge contracts (LayerZero)',   status: 'Passed',  findings: '0 critical · 3 medium (fixed)' },
    { firm: 'TonSec Internal',  date: 'Ongoing',    scope: 'Runtime + anomaly detection',    status: 'Active',  findings: 'Continuous monitoring' },
  ],
  events: [
    { date: '2024-12-03', type: 'info',    msg: 'Scheduled rebalance executed across 847 active vaults' },
    { date: '2024-12-01', type: 'warning', msg: 'Unusual volume spike on BOLT/TON pool — TonSec monitoring active' },
    { date: '2024-11-28', type: 'info',    msg: 'Parameter update applied after 48 h timelock expiry (multisig 3-of-5 approved)' },
    { date: '2024-11-22', type: 'info',    msg: 'Insurance fund topped up to $4.2M via protocol fee accrual' },
    { date: '2024-11-15', type: 'success', msg: 'Trail of Bits audit completed — all medium findings resolved, 0 critical' },
    { date: '2024-11-03', type: 'warning', msg: 'DeDust FNZ/USDT pool anomaly detected — position auto-paused for 4 h, resumed after review' },
  ],
}

export const BRIDGE_TOKENS = [
  { symbol: 'USDC', name: 'USD Coin',       decimals: 6  },
  { symbol: 'USDT', name: 'Tether USD',     decimals: 6  },
  { symbol: 'WETH', name: 'Wrapped Ether',  decimals: 18 },
  { symbol: 'WBTC', name: 'Wrapped Bitcoin',decimals: 8  },
  { symbol: 'TON',  name: 'Toncoin',        decimals: 9  },
  { symbol: 'MATIC',name: 'Polygon',        decimals: 18 },
  { symbol: 'ETH',  name: 'Ether (Base)',   decimals: 18 },
  { symbol: 'BNB',  name: 'BNB',            decimals: 18 },
]

export const PLATFORM_STATS = [
  { label: 'Total TVL',      value: '$1.24B' },
  { label: 'Active Vaults',  value: '14,293' },
  { label: '24h Volume',     value: '$247M'  },
  { label: 'Pools Tracked',  value: '2,400+' },
]
