export const POOLS = [
  // TON — STON.fi
  { id: 1,  pair: 'TON/USDT',      chain: 'TON',     dex: 'STON.fi',    apy: 18.5,  tvl: 45200000,  vol24h: 3200000,  ilRisk: 'Medium'   },
  { id: 2,  pair: 'TON/USDC',      chain: 'TON',     dex: 'STON.fi',    apy: 16.8,  tvl: 32100000,  vol24h: 2100000,  ilRisk: 'Medium'   },
  { id: 3,  pair: 'STON/TON',      chain: 'TON',     dex: 'STON.fi',    apy: 42.3,  tvl: 8700000,   vol24h: 1400000,  ilRisk: 'High'     },
  { id: 4,  pair: 'BOLT/TON',      chain: 'TON',     dex: 'STON.fi',    apy: 67.4,  tvl: 2100000,   vol24h: 890000,   ilRisk: 'Very High' },
  { id: 5,  pair: 'jUSDT/jUSDC',   chain: 'TON',     dex: 'STON.fi',    apy: 5.2,   tvl: 22400000,  vol24h: 4100000,  ilRisk: 'None'     },
  { id: 6,  pair: 'STON/USDT',     chain: 'TON',     dex: 'STON.fi',    apy: 55.3,  tvl: 3200000,   vol24h: 1100000,  ilRisk: 'Very High' },
  { id: 7,  pair: 'NOT/TON',       chain: 'TON',     dex: 'STON.fi',    apy: 78.9,  tvl: 4100000,   vol24h: 2200000,  ilRisk: 'Very High' },
  // TON — DeDust
  { id: 8,  pair: 'TON/USDT',      chain: 'TON',     dex: 'DeDust',     apy: 21.2,  tvl: 38500000,  vol24h: 2900000,  ilRisk: 'Medium'   },
  { id: 9,  pair: 'TON/WBTC',      chain: 'TON',     dex: 'DeDust',     apy: 15.7,  tvl: 18300000,  vol24h: 1200000,  ilRisk: 'Medium'   },
  { id: 10, pair: 'TON/ETH',       chain: 'TON',     dex: 'DeDust',     apy: 19.4,  tvl: 12600000,  vol24h: 980000,   ilRisk: 'Medium'   },
  { id: 11, pair: 'SCALE/TON',     chain: 'TON',     dex: 'DeDust',     apy: 89.2,  tvl: 1400000,   vol24h: 670000,   ilRisk: 'Very High' },
  { id: 12, pair: 'FNZ/USDT',      chain: 'TON',     dex: 'DeDust',     apy: 112.4, tvl: 800000,    vol24h: 450000,   ilRisk: 'Very High' },
  { id: 13, pair: 'hTON/TON',      chain: 'TON',     dex: 'DeDust',     apy: 6.8,   tvl: 28900000,  vol24h: 1800000,  ilRisk: 'Low'      },
  { id: 14, pair: 'tgBTC/TON',     chain: 'TON',     dex: 'DeDust',     apy: 14.2,  tvl: 9800000,   vol24h: 780000,   ilRisk: 'Medium'   },
  // Polygon — Uniswap v3
  { id: 15, pair: 'WETH/USDC',     chain: 'Polygon', dex: 'Uniswap v3', apy: 12.3,  tvl: 89400000,  vol24h: 12400000, ilRisk: 'Medium'   },
  { id: 16, pair: 'WBTC/WETH',     chain: 'Polygon', dex: 'Uniswap v3', apy: 8.7,   tvl: 67200000,  vol24h: 8900000,  ilRisk: 'Low'      },
  { id: 17, pair: 'MATIC/USDC',    chain: 'Polygon', dex: 'Uniswap v3', apy: 18.9,  tvl: 34700000,  vol24h: 5600000,  ilRisk: 'Medium'   },
  { id: 18, pair: 'WETH/USDT',     chain: 'Polygon', dex: 'Uniswap v3', apy: 11.8,  tvl: 78300000,  vol24h: 10200000, ilRisk: 'Medium'   },
  { id: 19, pair: 'WBTC/USDC',     chain: 'Polygon', dex: 'Uniswap v3', apy: 7.2,   tvl: 52100000,  vol24h: 7100000,  ilRisk: 'Low'      },
  // Polygon — QuickSwap
  { id: 20, pair: 'MATIC/USDC',    chain: 'Polygon', dex: 'QuickSwap',  apy: 22.4,  tvl: 28900000,  vol24h: 4200000,  ilRisk: 'Medium'   },
  { id: 21, pair: 'QUICK/MATIC',   chain: 'Polygon', dex: 'QuickSwap',  apy: 45.8,  tvl: 9200000,   vol24h: 2800000,  ilRisk: 'High'     },
  { id: 22, pair: 'WETH/MATIC',    chain: 'Polygon', dex: 'QuickSwap',  apy: 19.7,  tvl: 41300000,  vol24h: 6100000,  ilRisk: 'Medium'   },
  { id: 23, pair: 'USDC/USDT',     chain: 'Polygon', dex: 'QuickSwap',  apy: 4.8,   tvl: 156200000, vol24h: 21000000, ilRisk: 'None'     },
  { id: 24, pair: 'WBTC/MATIC',    chain: 'Polygon', dex: 'QuickSwap',  apy: 24.3,  tvl: 15800000,  vol24h: 3400000,  ilRisk: 'High'     },
  { id: 25, pair: 'ANKR/MATIC',    chain: 'Polygon', dex: 'QuickSwap',  apy: 31.2,  tvl: 7400000,   vol24h: 1900000,  ilRisk: 'High'     },
  // Polygon — Balancer
  { id: 26, pair: 'WETH/WBTC/USDC',chain: 'Polygon', dex: 'Balancer',   apy: 9.4,   tvl: 45600000,  vol24h: 7800000,  ilRisk: 'Low'      },
  { id: 27, pair: 'MATIC/WETH/BAL', chain: 'Polygon', dex: 'Balancer',  apy: 16.2,  tvl: 22100000,  vol24h: 3200000,  ilRisk: 'Medium'   },
  { id: 28, pair: 'stMATIC/MATIC',  chain: 'Polygon', dex: 'Balancer',  apy: 7.8,   tvl: 34200000,  vol24h: 2900000,  ilRisk: 'Low'      },
  { id: 29, pair: 'USDC/USDT/DAI',  chain: 'Polygon', dex: 'Balancer',  apy: 4.1,   tvl: 98700000,  vol24h: 15600000, ilRisk: 'None'     },
  { id: 30, pair: 'BAL/WETH',       chain: 'Polygon', dex: 'Balancer',  apy: 28.4,  tvl: 8300000,   vol24h: 2100000,  ilRisk: 'High'     },
]

export const LENDING = [
  { id: 1,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'USDC',  supplyAPY: 4.21, borrowAPY: 6.82, utilization: 78, tvl: 234500000 },
  { id: 2,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'USDT',  supplyAPY: 3.91, borrowAPY: 6.14, utilization: 74, tvl: 189200000 },
  { id: 3,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'WETH',  supplyAPY: 1.82, borrowAPY: 3.24, utilization: 62, tvl: 456700000 },
  { id: 4,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'WBTC',  supplyAPY: 0.94, borrowAPY: 2.41, utilization: 48, tvl: 312400000 },
  { id: 5,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'MATIC', supplyAPY: 2.31, borrowAPY: 4.12, utilization: 67, tvl: 87600000  },
  { id: 6,  protocol: 'AAVE v3',    chain: 'Polygon', asset: 'DAI',   supplyAPY: 3.74, borrowAPY: 5.93, utilization: 72, tvl: 145300000 },
  { id: 7,  protocol: 'Evaa',       chain: 'TON',     asset: 'TON',   supplyAPY: 5.12, borrowAPY: 8.34, utilization: 69, tvl: 78400000  },
  { id: 8,  protocol: 'Evaa',       chain: 'TON',     asset: 'USDT',  supplyAPY: 6.23, borrowAPY: 9.11, utilization: 81, tvl: 45600000  },
  { id: 9,  protocol: 'Evaa',       chain: 'TON',     asset: 'USDC',  supplyAPY: 5.81, borrowAPY: 8.72, utilization: 77, tvl: 32100000  },
  { id: 10, protocol: 'Evaa',       chain: 'TON',     asset: 'tgBTC', supplyAPY: 1.43, borrowAPY: 3.82, utilization: 45, tvl: 18700000  },
  { id: 11, protocol: 'Tonstakers', chain: 'TON',     asset: 'TON',   supplyAPY: 5.83, borrowAPY: null, utilization: null, tvl: 234000000 },
  { id: 12, protocol: 'Bemo',       chain: 'TON',     asset: 'TON',   supplyAPY: 6.11, borrowAPY: null, utilization: null, tvl: 178000000 },
]

export const STRATEGIES = [
  {
    id: 'super-safe',
    tier: 'Super Safe',
    name: 'Capital Preservation',
    apyMin: 4,
    apyMax: 7,
    color: '#00d4aa',
    riskScore: 1,
    protocols: ['AAVE v3', 'Evaa'],
    chains: ['Polygon', 'TON'],
    ilRisk: false,
    liquidationRisk: false,
    description: 'Stablecoin-only lending. Deposits split across AAVE v3 (Polygon) and Evaa (TON), auto-rebalancing toward the highest supply rate. Zero LP exposure — no impermanent loss possible.',
    allocation: [
      { label: 'AAVE v3 — USDC/USDT', pct: 45, color: '#8247e5' },
      { label: 'AAVE v3 — DAI',       pct: 25, color: '#6432b8' },
      { label: 'Evaa — USDT',         pct: 20, color: '#0098ea' },
      { label: 'Evaa — USDC',         pct: 10, color: '#0076bb' },
    ],
  },
  {
    id: 'safe',
    tier: 'Safe',
    name: 'Balanced Growth',
    apyMin: 9,
    apyMax: 15,
    color: '#0098ea',
    riskScore: 2,
    protocols: ['DeDust', 'Uniswap v3'],
    chains: ['TON', 'Polygon'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'Correlated-asset LPs with low impermanent loss. WBTC/WETH and WETH/USDC on Uniswap v3 with ±10% concentrated ranges, hTON/TON and tgBTC/TON on DeDust. Assets tend to co-move, keeping IL minimal.',
    allocation: [
      { label: 'Uniswap v3 — WBTC/WETH',  pct: 35, color: '#f97316' },
      { label: 'Uniswap v3 — WETH/USDC',  pct: 30, color: '#fb923c' },
      { label: 'DeDust — hTON/TON',       pct: 20, color: '#0098ea' },
      { label: 'DeDust — tgBTC/TON',      pct: 15, color: '#0076bb' },
    ],
  },
  {
    id: 'middle',
    tier: 'Middle',
    name: 'Yield Maximizer',
    apyMin: 20,
    apyMax: 40,
    color: '#f97316',
    riskScore: 3,
    protocols: ['STON.fi', 'QuickSwap'],
    chains: ['TON', 'Polygon'],
    ilRisk: true,
    liquidationRisk: false,
    description: 'Multi-asset LP farming with aggressive weekly rebalancing. TON/USDT and TON/USDC on STON.fi, MATIC/USDC and WETH/MATIC on QuickSwap. Significant IL risk if assets diverge >20% during a rebalance cycle.',
    allocation: [
      { label: 'STON.fi — TON/USDT',      pct: 30, color: '#0098ea' },
      { label: 'QuickSwap — MATIC/USDC',  pct: 28, color: '#8247e5' },
      { label: 'QuickSwap — WETH/MATIC',  pct: 24, color: '#6a35d4' },
      { label: 'STON.fi — TON/USDC',      pct: 18, color: '#0076bb' },
    ],
  },
  {
    id: 'risky',
    tier: 'Alpha Seeker',
    name: 'Alpha Seeker',
    apyMin: 50,
    apyMax: 120,
    color: '#ef4444',
    riskScore: 4,
    protocols: ['STON.fi', 'DeDust', 'QuickSwap'],
    chains: ['TON', 'Polygon'],
    ilRisk: true,
    liquidationRisk: true,
    description: 'High-turnover strategy targeting new pool incentives and leveraged positions. Rotates weekly into highest-APY opportunities. Includes 2× leveraged LP on QuickSwap. Participating pools have <6 months track record. Full capital loss is a real possibility.',
    allocation: [
      { label: 'STON.fi — BOLT/TON',      pct: 25, color: '#0098ea' },
      { label: 'DeDust — SCALE/TON',      pct: 22, color: '#0076bb' },
      { label: 'QuickSwap — QUICK/MATIC', pct: 28, color: '#8247e5' },
      { label: 'Balancer — BAL/WETH',     pct: 25, color: '#6a35d4' },
    ],
  },
]

export const SECURITY_DATA = {
  tonsecStatus: 'Operational',
  vaultHealth: 98.7,
  insuranceFund: 4200000,
  totalScreened: 1847293,
  anomaliesDetected: 3,
  pausedContracts: 0,
  timelockHours: 48,
  multiSig: '3-of-5',
  audits: [
    { firm: 'Trail of Bits',    date: '2024-11-15', scope: 'Full protocol audit',           status: 'Passed',  findings: '0 critical · 2 medium (fixed)' },
    { firm: 'Certik',           date: '2024-09-08', scope: 'FunC smart contracts',           status: 'Passed',  findings: '0 critical · 1 high (fixed) · 4 medium (fixed)' },
    { firm: 'SlowMist',         date: '2024-06-22', scope: 'Bridge contracts (LayerZero)',   status: 'Passed',  findings: '0 critical · 3 medium (fixed)' },
    { firm: 'TonSec Internal',  date: 'Ongoing',    scope: 'Runtime + anomaly detection',    status: 'Active',  findings: 'Continuous monitoring' },
  ],
  events: [
    { date: '2024-12-03', type: 'info',    msg: 'Scheduled rebalance executed across 847 active vaults' },
    { date: '2024-12-01', type: 'warning', msg: 'Unusual volume spike on BOLT/TON pool — TonSec monitoring active' },
    { date: '2024-11-28', type: 'info',    msg: 'Parameter update applied after 48 h timelock expiry (multisig 3-of-5 approved)' },
    { date: '2024-11-22', type: 'info',    msg: 'Insurance fund topped up to $4.2M via protocol fee accrual' },
    { date: '2024-11-15', type: 'success', msg: 'Trail of Bits audit completed — all medium findings resolved, 0 critical' },
    { date: '2024-11-03', type: 'warning', msg: 'DeDust FNZ/USDT pool anomaly detected — position auto-paused for 4 h, resumed after review' },
  ],
}

export const BRIDGE_TOKENS = [
  { symbol: 'USDC', name: 'USD Coin',       decimals: 6  },
  { symbol: 'USDT', name: 'Tether USD',     decimals: 6  },
  { symbol: 'WETH', name: 'Wrapped Ether',  decimals: 18 },
  { symbol: 'WBTC', name: 'Wrapped Bitcoin',decimals: 8  },
  { symbol: 'TON',  name: 'Toncoin',        decimals: 9  },
  { symbol: 'MATIC',name: 'Polygon',        decimals: 18 },
]

export const PLATFORM_STATS = [
  { label: 'Total TVL',      value: '$1.24B' },
  { label: 'Active Vaults',  value: '14,293' },
  { label: '24h Volume',     value: '$247M'  },
  { label: 'Pools Tracked',  value: '2,400+' },
]
